### ISSUE TITLE
Missing other OU PAPs in the List of my assigned PAPs per OU

### ISSUE THREAD

**Issue by AlexEstoesta** [mlab817/ipms#12]
Per my OU assignments , there is No Rice, Corn, BAFS-ILD, PRDP, NMIS, NFA, RFOs IVB and VI, Regulatory Program. Only that of BAI was uploaded so far.

**Comment by mlab817** [comment]
As I've mentioned in my email, I only loaded some sample PAPs. Will update once we have the final assignments.
