### ISSUE TITLE
Error when Editing PAPs

### ISSUE THREAD

**Issue by AlexEstoesta** [mlab817/ipms#13]
Had to refresh the page at least once to get to the proper webpage for editing a specific PAP

**Comment by mlab817** [comment]
"What does had to refresh mean?" loading forever? an error occurred? blank page?

**Comment by AlexEstoesta** [comment]
A, the error I’ve noticed is that the edit page only displays half of the pap information to be edited, it can be said that the page didn’t load properly so I had to refresh it.

**Comment by AlexEstoesta** [comment]
Also took note of your comments on the other observations/suggestions i’ve listed. Thanks again.
