### ISSUE TITLE
Adding New PAP Error

### ISSUE THREAD

**Issue by aleckarlo** [mlab817/ipms#7]
![image](https://user-images.githubusercontent.com/66451064/138543426-5a99e703-49ff-4c00-bcd4-67b14c77f184.png)

Error shown right after adding a new PAP. Tried signing out and in again, and add the same PAP Title, however it says that the said title is already taken. Added another new PAP and still get the same error.

**Comment by aleckarlo** [comment]
BTW, also tried searching the recently-added PAP but it did not show in My PAPs List

**Comment by mlab817** [comment]
Will review this. It has to do with incorrect permissions for IPD staff.

**Comment by mlab817** [comment]
same as #14
