### ISSUE TITLE
Just a realization on investment targets...

### ISSUE THREAD

**Issue by aleckarlo** [mlab817/ipms#9]
Although costs from 2017-2021 can be reflected in the Financial Accomplishments, don't we might still need a part to show the overall TOTAL PROJECT COST wherein we could input it manually, like before? I think this will apply mostly to old ongoing projects

**Comment by mlab817** [comment]
I omitted the project cost because as you may have realized, it will no longer be consistent and cannot be used for checking as initially intended.

Will add it back but let's ensure that this is well-defined in the data requirements.
